version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /home/app1/node_modules
      - .:/home/app1
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /home/app1/node_modules
      - .:/home/app1
    command: ["npm", "run", "test"]
